name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Tests run

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 16.x]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format-check