name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: action/checkout@v2
    - name: Setup Node
      uses: action/setup-node@v2
      with:
        node-version: 18.16
    - name: Install deps
        run: npm ci
    - name: Run tests
        run" npm test